# Generated by Django 3.2.5 on 2022-02-07 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HSMS', '0004_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HSMS.service_category'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature_image',
            field=models.ImageField(null=True, upload_to='service_image'),
        ),
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HSMS.subcategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='service_image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
