# Generated by Django 4.0.2 on 2022-03-05 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HSMS', '0006_remove_service_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Order', 'Order'), ('Cencel', 'Cencel')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSMS.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
