# Generated by Django 4.0.2 on 2022-03-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSMS', '0009_booking_service_provider_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='customer',
        ),
    ]
