# Generated by Django 4.0.2 on 2022-03-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSMS', '0010_rename_user_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
    ]
