# Generated by Django 4.0.2 on 2022-03-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HSMS', '0014_service_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSMS.customer')),
                ('serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSMS.service')),
            ],
        ),
    ]
